services:
  redis:
    image: redis:7
    container_name: redis-limiter
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env

  benchmark:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: benchmark-tester
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - RATE_LIMIT_IP=10
      - BLOCK_DURATION_IP=10
      - RATE_LIMIT_TOKEN_DEFAULT=5
      - BLOCK_DURATION_TOKEN=10
    command: ["go", "test", "-bench=.", "./test"]

volumes:
  redis-data: